apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-scanner-vul.fullname" . }}
  labels:
{{ include "harbor-scanner-vul.labels" . | indent 4 }}
type: Opaque
data:
  gitHubToken: {{ .Values.scanner.vul.gitHubToken | default "" | b64enc | quote }}
