{{- if (.Values.scanner.vul.ignorePolicy) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor-scanner-vul.fullname" . }}-ignorepolicy
  labels:
{{ include "harbor-scanner-vul.labels" . | indent 4 }}
data:
  policy.rego: |
    {{ .Values.scanner.vul.ignorePolicy | nindent 4 }}
{{- end }}
